services:
  db:
    image: mysql:8.4
    container_name: basic-api-ktor-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: basic_api_ktor
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro

  adminer:
    image: adminer:4
    container_name: basic-api-ktor-adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "${ADMINER_HOST_PORT}:8080"

  app:
    image: pedrogv/basic-api-ktor:latest
    # build:  (eliminar o comentar)
    container_name: basic-api-ktor-app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_HOST_PORT: 3306
      MYSQL_DATABASE: basic_api_ktor
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${APP_HOST_PORT:-8080}:8080"
volumes:
  db_data:
